export const languages = {
  en: '🇺🇸 English', // English
  ja: '🇯🇵 Japanese', // Japanese
  'zh-CN': '🇨🇳 Chinese', // Chinese
  de: '🇩🇪 German', // German
  hi: '🇮🇳 Hindi', // Hindi
  fr: '🇫🇷 French', // French
  ko: '🇰🇷 Korean', // Korean
  it: '🇮🇹 Italian', // Italian
  es: '🇪🇸 Spanish', // Spanish
  id: '🇮🇩 Indonesian', // Indonesian
  nl: '🇳🇱 Dutch', // Dutch
  tr: '🇹🇷 Turkish', // Turkish
  fil: '🇵🇭 Filipino', // Filipino
  pl: '🇵🇱 Polish', // Polish
  sv: '🇸🇪 Swedish', // Swedish
  bg: '🇧🇬 Bulgarian', // Bulgarian
  ro: '🇷🇴 Romanian', // Romanian
  ar: '🇸🇦 Arabic', // Arabic
  cs: '🇨🇿 Czech', // Czech
  el: '🇬🇷 Greek', // Greek
  hr: '🇫🇮 Finnish', // Finnish
  ms: '🇲🇾 Malay', // Malay
  sk: '🇸🇰 Slovak', // Slovak
  da: '🇩🇰 Danish', // Danish
  uk: '🇺🇦 Ukrainian', // Ukrainian
  ru: '🇷🇺 Russian' // Russian
};
export default languages