export const voice_ids = {
  he: {
    mrk: "T0pkYhIZ7UMOc26gqqeX",
    "💂🏻‍♀️": "1BUhH8aaMvGMUdGAmWVM",
    "👨🏻‍🦳": "5Q0t7uMcjvnagumLfvZi",
    "👨🏾‍🦱": "pNInz6obpgDQGcFmaJgB",
    ";;": "Yko7PKHZNXotIFUBG7I9",
    "👱🏻‍♂️": "iP95p4xoKVk53GoZ742B",
    "👷🏻‍♂️": "yoZ06aMxZJJ28mfd3POQ",
    "🧔🏻‍♂️": "IKne3meq5aSn9XLyUdCD",
    "🤷🏻": "ODq5zmih8GrVes37Dizd",
    "👨🏻‍🦰": "CYw3kZ02Hs0563khs1Fj",
    "🥷🏼": "2EiwWnXFnvU5JabPnv8n",
    "🧙🏻‍♂️": "Zlb1dXrM653N07WRdFW3",
    "🧝🏻‍♂️": "SOYHLrjzK2X1ezoPC6cr",
    "🦹🏼‍♂️": "D38z5RcWu1voky8WS1ja",
    "👨🏾‍✈️": "flq6f7yk4E4fJM5XTYuZ",
    "🦸🏻‍♂️": "TxGEqnHWrfWFTfGW9XjX",
    "🤴🏻": "N2lVS1w4EtoT3dr4eOWO",
    "👨🏻‍🚀": "pqHfZKP75CvOlQylNhV4",
    "🧔🏻": "t0jbNlBVZ17f02VDIeMI",
    "🙆🏾‍♂️": "onwK4e9ZLuTAKqWW03F9",
    "💁🏼‍♂️": "TX3LPaxmHKxFdv7VOQHJ",
  },
  her: {
    "👩🏻‍⚖️": "pMsXgVXv3BLzUgSXRplE",
    "👩🏼": "XrExE9yKIg1WjnnlVkGX",
    "👱🏼‍♀️": "pFZP5JQG7iQjIQuC4Bku",
    "👸🏻": "21m00Tcm4TlvDq8ikWAM",
    "🦸🏻‍♀️": "z9fAnlkpzviPz146aGWa",
    "👩🏼‍🦱": "jsCqWAovK2LkecY7zXl4",
    "👩🏻‍🔬": "XB0fDUnXU5powFXDhCwa",
    "👩🏻‍💻": "Xb7hH8MSUJpSbSDYk0k2",
    "💆🏼‍♀️": "aEO01A4wXwd1O8GPgGlF",
    kirt: "YVyp28LAMQfmx8iIH88U",
    ogre: "8p0TKx5Y1nPHsQo3LByi",
    " mark": "UgBBYS2sOqTuMpoF3BR0",
    " bight": "OOk3INdXVLRmSaQoAX9D",
  },
  they: {
    "🧖🏻‍♀️": "LcfcDJNUP1GQjkzn1xUU",
    "🧖🏻‍♀️🧖🏻‍♀️": "eVItLK1UvXctxuaRV2Oq",
    "🙎🏼": "GBv7mTt0atIp3Br8iCZE",
    "💆🏼‍♀️": "piTKgcLEGmPE4e6mEKli",
    "🧏🏼": "g5CIjZEefAph4nQFvHAz",
    "👩🏻‍🎤": "MF3mGyEYCl7XYWbV9V6O",
    "👩🏻‍✈️": "AZnzlk1XvdvUeBnXmlld",
  },
};

// export const voice_ids = {
//   he: {
//     "🔇 Silent": "",
//     "💂🏻‍♀️Alyx": "1BUhH8aaMvGMUdGAmWVM",
//     "👨🏻‍🦳 Paul": "5Q0t7uMcjvnagumLfvZi",
//     "👨🏾‍🦱 Adam": "pNInz6obpgDQGcFmaJgB",
//     "💂🏻‍♀️ Matthew": "Yko7PKHZNXotIFUBG7I9",
//     "👱🏻‍♂️ Chris": "iP95p4xoKVk53GoZ742B",
//     "👷🏻‍♂️ Sam": "yoZ06aMxZJJ28mfd3POQ",
//     "🧔🏻‍♂️ Charlie": "IKne3meq5aSn9XLyUdCD",
//     "🤷🏻 Patrick": "ODq5zmih8GrVes37Dizd",
//     "👨🏻‍🦰 Dave": "CYw3kZ02Hs0563khs1Fj",
//     "🥷🏼 Keenau": "2EiwWnXFnvU5JabPnv8n",
//     "🧙🏻‍♂️ Joseph": "Zlb1dXrM653N07WRdFW3",
//     "🧝🏻‍♂️ Harry": "SOYHLrjzK2X1ezoPC6cr",
//     "🦹🏼‍♂️ Fin": "D38z5RcWu1voky8WS1ja",
//     "👨🏾‍✈️ Michael": "flq6f7yk4E4fJM5XTYuZ",
//     "🦸🏻‍♂️ Josh": "TxGEqnHWrfWFTfGW9XjX",
//     "🤴🏻 Callum": "N2lVS1w4EtoT3dr4eOWO",
//     "👨🏻‍🚀 Bill": "pqHfZKP75CvOlQylNhV4",
//     "🧔🏻 Jessie": "t0jbNlBVZ17f02VDIeMI",
//     "🙆🏾‍♂️ Daniel": "onwK4e9ZLuTAKqWW03F9",
//     "💁🏼‍♂️ Liam": "TX3LPaxmHKxFdv7VOQHJ",

//   },
//   her: {
//     "👩🏻‍⚖️ Serena": "pMsXgVXv3BLzUgSXRplE",
//     "👩🏼 Matilda": "XrExE9yKIg1WjnnlVkGX",
//     "👱🏼‍♀️ Lily": "pFZP5JQG7iQjIQuC4Bku",
//     "👸🏻 Rachel": "21m00Tcm4TlvDq8ikWAM",
//     "🦸🏻‍♀️ Glinda": "z9fAnlkpzviPz146aGWa",
//     "👩🏼‍🦱 Freya": "jsCqWAovK2LkecY7zXl4",
//     "👩🏻‍🔬 Charlotte": "XB0fDUnXU5powFXDhCwa",
//     "👩🏻‍💻 Alice": "Xb7hH8MSUJpSbSDYk0k2",
//   },
//   they: {
//     "🧖🏻‍♀️ Emily": "LcfcDJNUP1GQjkzn1xUU",
//     "🙎🏼 Thomas": "GBv7mTt0atIp3Br8iCZE",
//     "💆🏼‍♀️ Nicole": "piTKgcLEGmPE4e6mEKli",
//     "🧏🏼 Ethan": "g5CIjZEefAph4nQFvHAz",
//     "👩🏻‍🎤 Elli": "MF3mGyEYCl7XYWbV9V6O",
//     "👩🏻‍✈️ Domi": "AZnzlk1XvdvUeBnXmlld",

//   },
// };
